### ISSUE TITLE
Uploading large files returns 421 Data connection error ([Errno 5] Request Timeout: Request Timeout)

### ISSUE THREAD

**Issue by renoovodesign** [cloudfs/ftp-cloudfs#63] opened 2017-01-18 13:12 UTC
I use Plesk Backup Manager to connect to ftpcloudfs binary using FTP on the localhost.
Passive Mode is on. Its always worked well until last few weeks. I am trying to identify whether the issue comes from any of these: ftpcloudfs, Rackspace, Plesk Manager, CentOS 7

Small files (<512MB) are transferred over my Rackspace account just fine.

Large files do not send. In this instance the backup file is 3GB.
In my config, I have: split-large-files = 1024. Which used to work fine.
I get this from the Plesk Backup log: `INFO: Error 55 Failed sending data to the peer`
And this from ftpcloudfs.log:
```
STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181237.tar 125
Data connection error ([Errno 5] : )
None; transfer aborted.
```

I have tried deactivating split-large-files.
But I get the following:

```
421 Data connection error ([Errno 5] Request Timeout: Request Timeout)
* We got a 421 - timeout!
* control connection looks dead
* Closing connection 1
```

I have tried using Active mode instead of passive. Still the same issue.

```
[2017-01-18 13:15:25.135| 6060] INFO: < 200 Active data connection established.
[2017-01-18 13:15:25.135| 6060] INFO: * Connect data stream actively
[2017-01-18 13:15:25.135| 6060] INFO: > TYPE I
[2017-01-18 13:15:25.135| 6060] INFO: < 200 Type set to: Binary.
[2017-01-18 13:15:25.135| 6060] INFO: > STOR backup_tuesprecieuse.fr_1701181311.tar
[2017-01-18 13:15:25.135| 6060] INFO: < 125 Data connection already open. Transfer starting.
[2017-01-18 13:15:25.135| 6060] INFO: * Preparing for accepting server on data port
[2017-01-18 13:15:25.135| 6060] INFO: * Checking for server connect
[2017-01-18 13:15:25.135| 6060] INFO: * Ready to accept data connection from server
[2017-01-18 13:15:25.135| 6060] INFO: * Connection accepted from server
[2017-01-18 13:15:25.135| 6060] INFO: * Send failure: Connection reset by peer
[2017-01-18 13:15:25.135| 6060] INFO: * Closing connection 1
[2017-01-18 13:15:25.135| 6060] INFO: 
[2017-01-18 13:15:25.137| 6060] INFO: Error 55 Failed sending data to the peer
[2017-01-18 13:15:25.138| 6060] INFO: Pause before next attempt to upload file...
[2017-01-18 13:15:28.138| 6060] INFO: Trying to resume upload...
[2017-01-18 13:15:28.324| 6060] INFO: Curl output :
[2017-01-18 13:15:28.324| 6060] INFO: * Found bundle for host 127.0.0.1: 0xa61460
[2017-01-18 13:15:28.324| 6060] INFO: * Re-using existing connection! (#0) with host 127.0.0.1
[2017-01-18 13:15:28.324| 6060] INFO: * Connected to 127.0.0.1 (127.0.0.1) port 2021 (#0)
[2017-01-18 13:15:28.324| 6060] INFO: * Request has same path as previous transfer
[2017-01-18 13:15:28.324| 6060] INFO: > TYPE I
[2017-01-18 13:15:28.325| 6060] INFO: * ftp_perform ends with SECONDARY: 0
[2017-01-18 13:15:28.325| 6060] INFO: < 200 Type set to: Binary.
[2017-01-18 13:15:28.325| 6060] INFO: > SIZE backup_tuesprecieuse.fr_1701181311.tar
[2017-01-18 13:15:28.325| 6060] INFO: < 550 /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181311.tar is not retrievable.
[2017-01-18 13:15:28.325| 6060] INFO: > REST 0
[2017-01-18 13:15:28.325| 6060] INFO: < 350 Restarting at position 0.
[2017-01-18 13:15:28.325| 6060] INFO: * Remembering we are in dir "Backup/tuesprecieuse/"
[2017-01-18 13:15:28.325| 6060] INFO: * Connection #0 to host 127.0.0.1 left intact
[2017-01-18 13:15:28.325| 6060] INFO: 
[2017-01-18 13:15:28.325| 6060] INFO: Unable to resume interrupted upload. It seems like FTP server deleted the file, when the connection was lost. Try to repeat or perform upload manually

```

**Comment by reidrac** [comment] 2017-01-18 13:27
Can you check if any of the components have been updated recently (including ftpcloudfs).
Also it would be useful to run the FTP server in debug mode.

You need split-large-files. Default for swift in 5GB, but the provider (Rackspace) coul have changed that default.

Another thing you can try is to reduce the size of the parts. 1GB can be a big file to post using HTTP, so try something smaller; for example 250 (250MB). If you need to retrieve the backup later it won't make any difference, swift will manage the manifest just the same (there's a a difference if you go over 10k parts though).

**Comment by renoovodesign** [comment] 2017-01-18 15:01
I am using ftpcloudfs 0.35.
verbose = yes.

I have tried with 512MB split and 250MB split, it still fails the same way.
```
Data connection error ([Errno 5] : )
-> 426 None; transfer aborted.
```

Rackspace seem to have a limit of 5GB still https://developer.rackspace.com/docs/cloud-files/v1/general-api-info/limits/

Is it a case that the split function does not work properly anymore?

What do you mean by this: "(there's a a difference if you go over 10k parts though)"

**Comment by reidrac** [comment] 2017-01-18 15:06
That's what I'm trying to figure out!

Could also be an issue with Rackspace service or your connectivity with that service.

 Can you tell me if this started happening after you upgraded to 0.35 or did 0.35 worked until you starting having this issue?

**Comment by renoovodesign** [comment] 2017-01-18 15:09
I seem to remember getting this issue after having updated to 0.35.
I believe I was using 0.32 before, and it was fine.

**Comment by reidrac** [comment] 2017-01-18 15:23
Thanks, I'll investigate because in the last releases we have changed some bits related to large file support.

**Comment by renoovodesign** [comment] 2017-01-23 12:51
Any updates?

**Comment by reidrac** [comment] 2017-01-23 18:48
Not yet, I'll need some time to look at this.

**Comment by reidrac** [comment] 2017-02-12 08:06
Can I have the ftp-cloudfs log running on `--verbose` mode? (strip any secretes from it).

**Comment by renoovodesign** [comment] 2017-02-13 13:31
Hopefully this should help:

```
Jan 18 12:08:47 r************* ftpcloudfs[64598]: 127.0.0.1:59140-[r*************] USER 'r*************' logged in.
Jan 18 12:08:50 r************* ftpcloudfs[61858]: 127.0.0.1:59154-[] FTP session opened (connect)
Jan 18 12:08:50 r************* ftpcloudfs[61858]: 127.0.0.1:59154-[] FTP session closed (disconnect).
Jan 18 12:08:50 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] Authentication validated for user r*************
Jan 18 12:08:50 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] USER 'r*************' logged in.
Jan 18 12:08:50 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181208.tar 125
Jan 18 12:11:45 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] Data connection error ([Errno 5] : )
Jan 18 12:11:45 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] None; transfer aborted.
Jan 18 12:11:45 r************* ftpcloudfs[64626]: 127.0.0.1:59154-[r*************] FTP session closed (disconnect).
Jan 18 12:11:48 r************* ftpcloudfs[64598]: 127.0.0.1:59140-[r*************] FTP session closed (disconnect).
Jan 18 12:11:55 r************* ftpcloudfs[61858]: 127.0.0.1:59342-[] FTP session opened (connect)
Jan 18 12:11:55 r************* ftpcloudfs[61858]: 127.0.0.1:59342-[] FTP session closed (disconnect).
Jan 18 12:11:55 r************* ftpcloudfs[64988]: 127.0.0.1:59342-[r*************] Failed to authenticate user r*************: [Errno 5] username/password required:
Jan 18 12:11:56 r************* ftpcloudfs[61858]: 127.0.0.1:59344-[] FTP session opened (connect)
Jan 18 12:11:56 r************* ftpcloudfs[61858]: 127.0.0.1:59344-[] FTP session closed (disconnect).
Jan 18 12:11:56 r************* ftpcloudfs[64998]: 127.0.0.1:59344-[r*************] Authentication validated for user r*************
Jan 18 12:11:56 r************* ftpcloudfs[64998]: 127.0.0.1:59344-[r*************] USER 'v' logged in.
Jan 18 12:11:56 r************* ftpcloudfs[64998]: 127.0.0.1:59344-[r*************] FTP session closed (disconnect).

```

Then later on

```
Jan 18 12:32:26 r************* ftpcloudfs[1255]: 127.0.0.1:60358-[r*************] Authentication validated for user r*************
Jan 18 12:32:26 r************* ftpcloudfs[1255]: 127.0.0.1:60358-[r*************] USER 'r*************' logged in.
Jan 18 12:32:27 r************* ftpcloudfs[1255]: 127.0.0.1:60358-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar 125
Jan 18 12:34:26 r************* ftpcloudfs[61858]: 127.0.0.1:60524-[] FTP session opened (connect)
Jan 18 12:34:26 r************* ftpcloudfs[61858]: 127.0.0.1:60524-[] FTP session closed (disconnect).
Jan 18 12:34:26 r************* ftpcloudfs[1514]: 127.0.0.1:60524-[r*************] Authentication validated for user r*************
Jan 18 12:34:26 r************* ftpcloudfs[1514]: 127.0.0.1:60524-[r*************] USER 'r*************' logged in.
Jan 18 12:34:27 r************* ftpcloudfs[1514]: 127.0.0.1:60524-[r*************] FTP session closed (disconnect).
Jan 18 12:34:27 r************* ftpcloudfs[61858]: 127.0.0.1:60536-[] FTP session opened (connect)
Jan 18 12:34:27 r************* ftpcloudfs[61858]: 127.0.0.1:60536-[] FTP session closed (disconnect).
Jan 18 12:34:27 r************* ftpcloudfs[1534]: 127.0.0.1:60536-[r*************] Authentication validated for user r*************
Jan 18 12:34:27 r************* ftpcloudfs[1534]: 127.0.0.1:60536-[r*************] USER 'r*************' logged in.
Jan 18 12:34:32 r************* ftpcloudfs[1534]: 127.0.0.1:60536-[r*************] FTP session closed (disconnect).
Jan 18 12:35:02 r************* ftpcloudfs[1255]: 127.0.0.1:60358-[r*************] Data connection error ([Errno 5] Request Timeout: Request Timeout)
Jan 18 12:35:02 r************* ftpcloudfs[1255]: 127.0.0.1:60358-[r*************] FTP session closed (disconnect).
Jan 18 12:35:02 r************* ftpcloudfs[61858]: 127.0.0.1:60556-[] FTP session opened (connect)
Jan 18 12:35:02 r************* ftpcloudfs[61858]: 127.0.0.1:60556-[] FTP session closed (disconnect).
Jan 18 12:35:02 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] Authentication validated for user r*************
Jan 18 12:35:02 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] USER 'r*************' logged in.
Jan 18 12:35:02 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar1 125
Jan 18 12:35:19 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar2 125
Jan 18 12:35:35 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar3 125
Jan 18 12:35:51 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar4 125
Jan 18 12:36:07 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181232.tar5 125
Jan 18 12:36:24 r************* ftpcloudfs[1220]: 127.0.0.1:60338-[r*************] FTP session closed (disconnect).
Jan 18 12:36:24 r************* ftpcloudfs[1659]: 127.0.0.1:60556-[r*************] FTP session closed (disconnect).
Jan 18 12:36:27 r************* ftpcloudfs[61858]: 127.0.0.1:60656-[] FTP session opened (connect)
Jan 18 12:36:27 r************* ftpcloudfs[61858]: 127.0.0.1:60656-[] FTP session closed (disconnect).
Jan 18 12:36:27 r************* ftpcloudfs[1826]: 127.0.0.1:60656-[r*************] Authentication validated for user r*************
Jan 18 12:36:27 r************* ftpcloudfs[1826]: 127.0.0.1:60656-[r*************] USER 'r*************' logged in.
Jan 18 12:36:27 r************* ftpcloudfs[1826]: 127.0.0.1:60656-[r*************] FTP session closed (disconnect).
Jan 18 12:36:28 r************* ftpcloudfs[61858]: 127.0.0.1:60668-[] FTP session opened (connect)
Jan 18 12:36:28 r************* ftpcloudfs[61858]: 127.0.0.1:60668-[] FTP session closed (disconnect).
Jan 18 12:36:28 r************* ftpcloudfs[1837]: 127.0.0.1:60668-[r*************] Authentication validated for user r*************
Jan 18 12:36:28 r************* ftpcloudfs[1837]: 127.0.0.1:60668-[r*************] USER 'r*************' logged in.
Jan 18 12:36:28 r************* ftpcloudfs[1837]: 127.0.0.1:60668-[r*************] FTP session closed (disconnect).
Jan 18 12:36:29 r************* ftpcloudfs[61858]: 127.0.0.1:60680-[] FTP session opened (connect)
Jan 18 12:36:29 r************* ftpcloudfs[61858]: 127.0.0.1:60680-[] FTP session closed (disconnect).
Jan 18 12:36:29 r************* ftpcloudfs[1849]: 127.0.0.1:60680-[r*************] Authentication validated for user r*************
Jan 18 12:36:29 r************* ftpcloudfs[1849]: 127.0.0.1:60680-[r*************] USER 'r*************' logged in.
Jan 18 12:36:32 r************* ftpcloudfs[1849]: 127.0.0.1:60680-[r*************] FTP session closed (disconnect).
Jan 18 12:37:40 r************* ftpcloudfs[61858]: 127.0.0.1:60746-[] FTP session opened (connect)
Jan 18 12:37:40 r************* ftpcloudfs[61858]: 127.0.0.1:60746-[] FTP session closed (disconnect).
Jan 18 12:37:40 r************* ftpcloudfs[1951]: 127.0.0.1:60746-[r*************] Authentication validated for user r*************
Jan 18 12:37:40 r************* ftpcloudfs[1951]: 127.0.0.1:60746-[r*************] USER 'r*************' logged in.
Jan 18 12:37:40 r************* ftpcloudfs[1951]: 127.0.0.1:60746-[r*************] FTP session closed (disconnect).
Jan 18 12:37:41 r************* ftpcloudfs[61858]: 127.0.0.1:60758-[] FTP session opened (connect)
Jan 18 12:37:41 r************* ftpcloudfs[61858]: 127.0.0.1:60758-[] FTP session closed (disconnect).
Jan 18 12:37:41 r************* ftpcloudfs[1970]: 127.0.0.1:60758-[r*************] Authentication validated for user r*************
Jan 18 12:37:41 r************* ftpcloudfs[1970]: 127.0.0.1:60758-[r*************] USER 'r*************' logged in.
Jan 18 12:37:42 r************* ftpcloudfs[1970]: 127.0.0.1:60758-[r*************] FTP session closed (disconnect).
Jan 18 12:37:42 r************* ftpcloudfs[61858]: 127.0.0.1:60774-[] FTP session opened (connect)
Jan 18 12:37:42 r************* ftpcloudfs[61858]: 127.0.0.1:60774-[] FTP session closed (disconnect).
Jan 18 12:37:42 r************* ftpcloudfs[1992]: 127.0.0.1:60774-[r*************] Authentication validated for user r*************
Jan 18 12:37:42 r************* ftpcloudfs[1992]: 127.0.0.1:60774-[r*************] USER 'r*************' logged in.
Jan 18 12:37:44 r************* ftpcloudfs[61858]: 127.0.0.1:60790-[] FTP session opened (connect)
Jan 18 12:37:44 r************* ftpcloudfs[61858]: 127.0.0.1:60790-[] FTP session closed (disconnect).
Jan 18 12:37:44 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] Authentication validated for user r*************
Jan 18 12:37:44 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] USER 'r*************' logged in.
Jan 18 12:37:44 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] STOR /Backup/tuesprecieuse/backup_tuesprecieuse.fr_1701181237.tar 125
Jan 18 12:40:30 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] Data connection error ([Errno 5] : )
Jan 18 12:40:30 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] None; transfer aborted.
Jan 18 12:40:30 r************* ftpcloudfs[2025]: 127.0.0.1:60790-[r*************] FTP session closed (disconnect).
Jan 18 12:40:33 r************* ftpcloudfs[1992]: 127.0.0.1:60774-[r*************] FTP session closed (disconnect).
Jan 18 12:40:39 r************* ftpcloudfs[61858]: 127.0.0.1:60856-[] FTP session opened (connect)
Jan 18 12:40:39 r************* ftpcloudfs[61858]: 127.0.0.1:60856-[] FTP session closed (disconnect).
Jan 18 12:40:39 r************* ftpcloudfs[2413]: 127.0.0.1:60856-[r*************] Failed to authenticate user r*************: [Errno 5] username/password required:
Jan 18 12:40:40 r************* ftpcloudfs[61858]: 127.0.0.1:60858-[] FTP session opened (connect)
Jan 18 12:40:40 r************* ftpcloudfs[61858]: 127.0.0.1:60858-[] FTP session closed (disconnect).
Jan 18 12:40:40 r************* ftpcloudfs[2423]: 127.0.0.1:60858-[r*************] Authentication validated for user r*************
Jan 18 12:40:40 r************* ftpcloudfs[2423]: 127.0.0.1:60858-[r*************] USER 'r*************' logged in.
Jan 18 12:40:40 r************* ftpcloudfs[2423]: 127.0.0.1:60858-[r*************] FTP session closed (disconnect).
Jan 18 12:40:41 r************* ftpcloudfs[61858]: 127.0.0.1:60870-[] FTP session opened (connect)
Jan 18 12:40:41 r************* ftpcloudfs[61858]: 127.0.0.1:60870-[] FTP session closed (disconnect).
Jan 18 12:40:41 r************* ftpcloudfs[2436]: 127.0.0.1:60870-[r*************] Authentication validated for user r*************
Jan 18 12:40:41 r************* ftpcloudfs[2436]: 127.0.0.1:60870-[r*************] USER 'r*************' logged in.
Jan 18 12:40:41 r************* ftpcloudfs[2436]: 127.0.0.1:60870-[r*************] FTP session closed (disconnect).
Jan 18 12:40:42 r************* ftpcloudfs[2413]: 127.0.0.1:60856-[] USER 'r*************' failed login.
Jan 18 12:40:42 r************* ftpcloudfs[2413]: 127.0.0.1:60856-[] FTP session closed (disconnect).
```

**Comment by gold22** [comment] 2017-02-22 08:03
Plesk Backup Manager can reconnect and continue backup uploading but I think a lot of already uploaded data is lost in the local cache of ftp-cloudfs and this stops uploading. Is there ability to disable or restrict the local cache?

**Comment by reidrac** [comment] 2017-02-22 08:26
There's no local cache as you describe it.

ftpcloudfs stores the output some operations in a local cache for a very
short period of time, for example to speed up directory listings; but it
doesn't cache object data, and definitely not object data that is being
uploaded.

swift uses a HTTP based API, until the HTTP request has finished and we
get the response from the server, we don't know the result of the
operation. For example, if you're uploading 100MB and the operation
fails, only when the POST/PUT of those 100MB has finished we know the
HTTP response with the error.

This behaviour is perhaps what you're assuming is a local cache.

Sorry I didn't have time yet to check this; I'll try to free some time
to look at it ASAP.

**Comment by reidrac** [comment] 2017-02-26 19:44
@renoovodesign that log doesn't look like it has verbose logging enabled.

**Comment by renoovodesign** [comment] 2017-02-27 10:51
@reidrac my ftpcloudfs.conf has `verbose = yes`
Not sure what else I can do to make it more verbose.

**Comment by reidrac** [comment] 2017-02-27 11:01
That log wasn't verbose I'm afraid.

Can you run it on a console with `-f -v -l /tmp/ftpcloufs.log` and send me that log?

In this way it'll run in foreground mode, with verbose logging, and will save a copy of the logs in `/tmp/ftpcloudfs.log`.

**Comment by renoovodesign** [comment] 2017-02-27 13:02
I've emailed you a copy of my log file.

I’ve had Plesk team work on this issue for more than a month now. So it could be their fault rather than ftpcloudfs.
This time it seems to have worked fine with a 3GB backup. The backup got split into 1GB chunks fine.
However, when I do a full server backup (12.5GB), I now get a new issue:
`Unable to upload the backup to the FTP storage: Unable to resume an interrupted upload: Seek out of scope of a stream cache (current cache size: 261 MB, required size: 722 MB): The connectivity problem: (55) Failed sending data to the peer: Last FTP response: 125 Data connection already open. Transfer starting`

**Comment by renoovodesign** [comment] 2017-02-27 13:04
I've received additional information from the Plesk developers:

```
During investigation, it was checked that ftp-cloudfs do not support uploads resuming. 
--------------------------- 
# echo 123 | curl -T - -v -P - --ftp-pasv --ssl -k -u r****** ftp://ip:port/Backup/server/test-file.txt 
# echo 456 | curl -T - -a -v -P - --ftp-pasv --ssl -k -u r****** ftp://ip:port/Backup/server/test-file.txt 
# curl -v -P - --ftp-pasv --ssl -k -u r****** ftp://ip:port/Backup/server/test-file.txt 
Such storage types are not supported by Plesk. It is recommended to use another FTP storage. 
```

**Comment by reidrac** [comment] 2017-02-27 13:11
Yes, that's right: you can't resume uploads, only downloads.

That's because the cloud storage doesn't support it! Remember the object storage is not a real filesystem, we're faking lots of things here to provide a filesystem-alike experience using FTP.

So you think this is an issue with Plesk and not a ftpcloudfs problem, is that correct?

**Comment by renoovodesign** [comment] 2017-03-06 16:32
Yes it seems to be that Plesk Onyx (17) does not support cloud fs any more. Plesk 12.5 used to handle it just fine. They are planning to support these kind of file systems again in future.

**Comment by reidrac** [comment] 2017-03-06 20:08
Well, trying to resume uploads is one thing (unsupported), but I see client timeouts too.

I can't reproduce the problem. It would be useful if you could downgrade ftpcloudfs to the latest version that was working OK for you. If it doesn't work either then we can assume it is a problem with Plesk.

It would interesting to know which ftp client is Plesk using. I only test a few, but if there's a problem in the protocol is likely to be something we can report to pyftpdlib (the library used to implement the ftp server).

**Comment by gold22** [comment] 2017-03-07 17:43
Plesk uses [libcurl](https://curl.haxx.se/libcurl/). You can install [a trial version of Plesk](http://page.plesk.com/plesk-onyx-free-download), create a subscription, configure Backup Manager and back up the subscription to the FTP storage.

**Comment by reidrac** [comment] 2017-03-10 10:04
I don't have time to do that I'm afraid. We don't pretend we can support all FTP clients, we rely in pyftplib and there are some limitations that are well known.

I'm inclined to close this issue as it looks like an issue with Plesk (or the swift backend + Plesk retrying), but I'll try to review the log @renoovodesign sent me so I can be completely sure.

**Comment by reidrac** [comment] 2017-05-31 10:13
Couldn't see anything conclusive on that log, closing this as is not a bug in ftp-cloudfs but issues with the ftp client.

**Closed by reidrac** 2017-05-31 10:13 UTC
Labels: question
